# https://docs.docker.com/compose/
version: "1.0"

services:
  code-generator:
    image: ccr.ccs.tencentyun.com/opensrcdevelop/code-generator:latest
    container_name: code-generator
    ports:
      - "8081:8080"
    restart: on-failure
    environment:
      CODE_GEN_GITLAB_URL: https://gitlab.com
      CODE_GEN_GITLAB_GROUP_NAME: code-gen-group
      CODE_GEN_GITLAB_PAT: ********
      OAUTH2_GITLAB_CLIENT_ID: ********
      OAUTH2_GITLAB_CLIENT_SECRET: ********
      OAUTH2_GITLAB_REDIRECT_URI: http://127.0.0.1:8081/login/oauth2/code/gitlab
    volumes:
      - ./logs:/app/logs