# spring
spring:
  application:
    name: code-generator
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
  controller:
    path-prefix: /code/gen/api

# log
logging:
  config: ${LOGGING_CONFIG:classpath:logback.xml}

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: 'all'
      paths-to-match: '/code/gen/api/**'
      paths-to-exclude: '/code/gen/api/gitlab/**'
    - group: 'template'
      paths-to-match: '/code/gen/api/template/**'
    - group: 'generator'
      paths-to-match: '/code/gen/api/generator/**'
    - group: 'parameter-util'
      paths-to-match: '/code/gen/api/parameter-util/**'
    - group: 'user'
      paths-to-match: '/code/gen/api/user/**'
    - group: 'system'
      paths-to-match: '/code/gen/api/system/**'

# code-generator
code:
  gen:
    gitlab:
      url: ${CODE_GEN_GITLAB_URL}
      group-name: ${CODE_GEN_GITLAB_GROUP_NAME}
      pat: ${CODE_GEN_GITLAB_PAT}
    lsp:
      enabled: false

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health
---
# OAuth2
# https://docs.gitlab.com/ee/api/oauth2.html
spring:
  security:
    oauth2:
      client:
        registration:
          auth-server:
            provider: auth-server
            client-name: code-generator
            authorization-grant-type: authorization_code
            client-id: ${OAUTH2_AUTH_SERVER_CLIENT_ID}
            client-secret: ${OAUTH2_AUTH_SERVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_AUTH_SERVER_REDIRECT_URI}
            scope:
              - openid
        provider:
          auth-server:
            authorization-uri: ${auth.client.issuer}/oauth2/authorize
            token-uri: ${auth.client.issuer}/oauth2/token
            jwk-set-uri: ${auth.client.issuer}/oauth2/jwks
            user-name-attribute: username
