server:
  port: 8081

# spring
spring:
  application:
    name: code-generator
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
  controller:
    path-prefix: /code/gen/api

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: 'all'
      paths-to-match: '/code/gen/api/**'
      paths-to-exclude: '/code/gen/api/gitlab/**'
    - group: 'template'
      paths-to-match: '/code/gen/api/template/**'
    - group: 'generator'
      paths-to-match: '/code/gen/api/generator/**'
    - group: 'parameter-util'
      paths-to-match: '/code/gen/api/parameter-util/**'
    - group: 'user'
      paths-to-match: '/code/gen/api/user/**'
    - group: 'system'
      paths-to-match: '/code/gen/api/system/**'

# code-generator
code:
  gen:
    gitlab:
      url: https://gitlab.com
      group-name: code-gen-group
      pat: ${CODE_GEN_GITLAB_PAT}
    lsp:
      enabled: false

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health
---
# OAuth2
# https://docs.gitlab.com/ee/api/oauth2.html
spring:
  security:
    oauth2:
      client:
        registration:
          auth-server:
            provider: auth-server
            client-name: code-generator
            authorization-grant-type: authorization_code
            client-id: b1c4e737-0e0e-4a65-833f-2b68145d8692
            client-secret: LPEF5EVRWOWOINOP4JTWNI23BROYDIFASMX7NUIFYWVY5VQFD4RQK3N7CLXCDLWF
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/auth-server
            scope:
              - openid

        provider:
          auth-server:
            authorization-uri: ${auth.client.issuer}/oauth2/authorize
            token-uri: ${auth.client.issuer}/oauth2/token
            jwk-set-uri: ${auth.client.issuer}/oauth2/jwks
            user-name-attribute: username